version: '3.8'

services:
  oura_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.dlt:/oura_pipeline/.dlt
      - ./data:/oura_pipeline/data
      - ./dlt:/oura_pipeline/dlt
      - ./sqlmesh:/oura_pipeline/sqlmesh
    environment:
      # Add any environment variables you might need
      - PYTHONUNBUFFERED=1
    # Keep the container running
    tty: true
    stdin_open: true