services:
  oura_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.dlt:/oura_pipeline/.dlt
      - ./data:/oura_pipeline/data
      - ./dlt:/oura_pipeline/dlt
      - ./sqlmesh:/oura_pipeline/sqlmesh
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
      - "8080:8080"
    tty: true
    stdin_open: true